name: Scan with Android Linter
run-name: ${{ github.actor }} protecting code quality! 🛡️

on:
  pull_request:
    branches:
      - main
      - develop
      - 'releases/**'

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Action for Android Lint
      uses: yutailang0119/action-android-lint@v3.1.0
